//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "attachments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub container_id: Option<i32>,
    pub container_type: Option<String>,
    pub filename: String,
    pub disk_filename: String,
    pub filesize: i32,
    pub content_type: Option<String>,
    pub digest: Option<String>,
    pub downloads: i32,
    pub author_id: i32,
    pub created_on: Option<DateTime>,
    pub description: Option<String>,
    pub disk_directory: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
