//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "issues")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tracker_id: i32,
    pub project_id: i32,
    pub subject: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub due_date: Option<Date>,
    pub category_id: Option<i32>,
    pub status_id: i32,
    pub assigned_to_id: Option<i32>,
    pub priority_id: i32,
    pub fixed_version_id: Option<i32>,
    pub author_id: i32,
    pub lock_version: i32,
    pub created_on: Option<DateTime>,
    pub updated_on: Option<DateTime>,
    pub start_date: Option<Date>,
    pub done_ratio: i32,
    #[sea_orm(column_type = "Double", nullable)]
    pub estimated_hours: Option<f64>,
    pub parent_id: Option<i32>,
    pub root_id: Option<i32>,
    pub lft: Option<i32>,
    pub rgt: Option<i32>,
    pub is_private: bool,
    pub closed_on: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
