//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "journal_details")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub journal_id: i32,
    pub property: String,
    pub prop_key: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub old_value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub value: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
