//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "journals")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub journalized_id: i32,
    pub journalized_type: String,
    pub user_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_on: DateTime,
    pub private_notes: bool,
    pub updated_on: Option<DateTime>,
    pub updated_by_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
