//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod attachments;
pub mod email_addresses;
pub mod enumerations;
pub mod issue_categories;
pub mod issue_relations;
pub mod issue_statuses;
pub mod issues;
pub mod journal_details;
pub mod journals;
pub mod member_roles;
pub mod members;
pub mod projects;
pub mod projects_trackers;
pub mod roles;
pub mod tokens;
pub mod trackers;
pub mod users;
