//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::attachments::Entity as Attachments;
pub use super::email_addresses::Entity as EmailAddresses;
pub use super::enumerations::Entity as Enumerations;
pub use super::issue_categories::Entity as IssueCategories;
pub use super::issue_relations::Entity as IssueRelations;
pub use super::issue_statuses::Entity as IssueStatuses;
pub use super::issues::Entity as Issues;
pub use super::journal_details::Entity as JournalDetails;
pub use super::journals::Entity as Journals;
pub use super::member_roles::Entity as MemberRoles;
pub use super::members::Entity as Members;
pub use super::projects::Entity as Projects;
pub use super::projects_trackers::Entity as ProjectsTrackers;
pub use super::roles::Entity as Roles;
pub use super::tokens::Entity as Tokens;
pub use super::trackers::Entity as Trackers;
pub use super::users::Entity as Users;
