//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub homepage: Option<String>,
    pub is_public: bool,
    pub parent_id: Option<i32>,
    pub created_on: Option<DateTime>,
    pub updated_on: Option<DateTime>,
    #[sea_orm(unique)]
    pub identifier: Option<String>,
    pub status: i32,
    pub lft: Option<i32>,
    pub rgt: Option<i32>,
    pub inherit_members: bool,
    pub default_version_id: Option<i32>,
    pub default_assigned_to_id: Option<i32>,
    pub default_issue_query_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
