//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub position: Option<i32>,
    pub assignable: bool,
    pub builtin: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub permissions: Option<String>,
    pub issues_visibility: String,
    pub users_visibility: String,
    pub time_entries_visibility: String,
    pub all_roles_managed: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub settings: Option<String>,
    pub default_time_entry_activity_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
