//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub login: String,
    pub hashed_password: Option<String>,
    pub firstname: String,
    pub lastname: String,
    pub admin: bool,
    pub status: i32,
    pub last_login_on: Option<DateTime>,
    pub language: Option<String>,
    pub auth_source_id: Option<i32>,
    pub created_on: Option<DateTime>,
    pub updated_on: Option<DateTime>,
    pub r#type: Option<String>,
    pub mail_notification: String,
    pub salt: Option<String>,
    pub must_change_passwd: bool,
    pub passwd_changed_on: Option<DateTime>,
    pub twofa_scheme: Option<String>,
    pub twofa_totp_key: Option<String>,
    pub twofa_totp_last_used_at: Option<i32>,
    pub twofa_required: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
