---
# Usage:
# ansible-playbook -i devops/ansible/hosts.yml devops/ansible/dev.yml --vault-password-file ~/.ansible-vault/rsmine.pwd

- name: Deploy rsmine (dev)
  hosts: oect
  user: "{{ user }}"
  gather_facts: no
  vars_files:
    - vars/dev/vault.yml

  vars:
    app_name: rsmine
    apps_path: "{{ home }}/docker"
    app_path: "{{ apps_path }}/{{ app_name }}"
    compose_file: "{{ app_path }}/docker-compose.yml"
    config_file: "{{ app_path }}/config.toml"

    image_tag: "dev"
    postgres_db: rsmine
    postgres_user: rsmine

  tasks:
    - name: Ensure paths
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ apps_path }}"
        - "{{ app_path }}"

    - name: Copy docker-compose.yml
      ansible.builtin.template:
        src: dev/docker-compose.yml.j2
        dest: "{{ compose_file }}"
        mode: "0644"

    - name: Copy config.toml
      ansible.builtin.template:
        src: dev/config.toml.j2
        dest: "{{ config_file }}"
        mode: "0600"

    - name: Stop containers
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        state: absent

    - name: Pull images
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        pull: always
        state: present

    - name: Start containers
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        state: present
